### ISSUE TITLE
v3.0.0 Crashes sites

### ISSUE THREAD

**Issue by gmariani** [markjaquith/page-links-to#55] opened 2018-07-26 13:36 UTC
https://wordpress.org/support/topic/ver-3-0-crashes-wordpress/#post-10530144

```
Stack trace:
#0 /home/derry/public_html/wp-includes/class-wp-hook.php(286): CWS_PageLinksTo->wp_list_pages(‘\t<li class=”men…’, Array)
#1 /home/derry/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(‘\t<li class=”men…’, Array)
#2 /home/derry/public_html/wp-content/themes/Derry/library/navigation.php(325): apply_filters(‘wp_list_pages’, ‘\t<li class=”men…’, Array)
#3 /home/derry/public_html/wp-content/themes/Derry/library/navigation.php(191): theme_MenuWalker->walk(Array, Array)
#4 /home/derry/public_html/wp-content/themes/Derry/library/navigation.php(27): theme_get_list_pages(Array)
#5 /home/derry/public_html/wp-content/themes/Derry/library/widgets.php(142): theme_get_menu(Array)
#6 /home/derry/public_html/wp-include in /home/derry/public_html/wp-content/plugins/page-links-to/classes/plugin.php on line 650
[26-Jul-2018 00:24:39 UTC] PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function CWS_PageLinksTo::wp_list_pages(), 2 passed in /home/derry/public_html/wp-includes/class-wp-hook.php on line 286 and exactly 3 expected in /home/derry/public_html/wp-content/plugins/page-links-to/classes/plugin.php:650
```

**Comment by markjaquith** [comment] 2018-07-26 22:08
Duplicate of #54

Try this version:

https://github.com/markjaquith/page-links-to/archive/master.zip

**Closed by markjaquith** 2018-07-26 22:08 UTC
